
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                ImageSource = @"C:\vpjtestimagenew\MIXER\image50.jpg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);



            Console.WriteLine($"ImageSource: {@"C:\vpjtestimagenew\MIXER\image50.jpg"}");


            Console.WriteLine("\n\nPredicted Boxes:\n");
            Console.WriteLine(predictionResult);
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
